#!/bin/bash

text_colour="\[\033"

export black="${text_colour}[0;30m\]"
export blue="${text_colour}[0;34m\]"
export cyan="${text_colour}[0;36m\]"
export red="${text_colour}[0;31m\]"
export purple="${text_colour}[0;35m\]"
export brown="${text_colour}[0;33m\]"
export green="${text_colour}[0;32m\]"
export magenta="${text_colour}[1;31m\]"
export orange="${text_colour}[1;33m\]"
export orange="${text_colour}[1;37m\]"
export light_grey="${text_colour}[0;37m\]"
export dark_grey="${text_colour}[1;30m\]"
export light_blue="${text_colour}[1;32m\]"
export light_green="${text_colour}[1;32m\]"
export light_cyan="${text_colour}[1;36m\]"
export light_red="${text_colour}[1;31m\]"
export light_purple="${text_colour}[1;35m\]"
export yellow="${text_colour}[1;33m\]"
export white="${text_colour}[1;37m\]"
export reset="${text_colour}[m\]"
