# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem "mdl"
gem "sass"
#gem "sqlint"
gem "guard"
gem "guard-shell"
gem "guard-sass"
gem "guard-phpunit"
gem "guard-mocha-node"
gem "guard-compass"
gem "guard-livereload"
gem "guard-concat"
gem "guard-webpack"
