# A sample Gemfile
source "https://rubygems.org"

gem "mdl"
gem "sass"
gem "guard"
# gem "rails"
gem "guard-sass"
gem "guard-shell"
gem "guard-concat"
gem "guard-webpack"
gem "guard-compass"
gem "guard-phpunit"
gem "guard-mocha-node"
gem "guard-livereload"
